In [1]:
import pandas as pd

URL = "http://data.insideairbnb.com/france/ile-de-france/paris/2024-09-06/visualisations/listings.csv"
df = pd.read_csv(URL)
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,371299,Marais Rue des Archives refait à neuf février ...,1870265,Thomas,NaN,Hôtel-de-Ville,48.85751,2.35511,Entire home/apt,185.0,3,601,2024-09-06,3.97,3,307,54,7510300547558
1,371862,loft in Paris (Belleville),1872631,Veronique,NaN,Entrepôt,48.87151,2.37219,Entire home/apt,250.0,4,50,2023-08-14,0.34,1,9,0,7511000320406
2,372879,Appartement complet au centre de Paris.,1876396,Samuel,NaN,Gobelins,48.83593,2.35108,Entire home/apt,85.0,30,171,2024-08-15,2.01,3,151,1,"Available with a mobility lease only (""bail mo..."
3,375434,"Luxurious Art & Design Flat, 180m2, Champs Ely...",683140,Oscar,NaN,Élysée,48.86680,2.30972,Entire home/apt,NaN,3,22,2023-07-15,0.15,1,0,0,7510806561916
4,378897,Little flat near Montmartre,1902818,Lorraine,NaN,Opéra,48.88285,2.33462,Entire home/apt,110.0,3,28,2024-07-30,0.19,1,6,2,7511805895013


In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95461 entries, 0 to 95460
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              95461 non-null  int64  
 1   name                            95461 non-null  str    
 2   host_id                         95461 non-null  int64  
 3   host_name                       95455 non-null  str    
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   95461 non-null  str    
 6   latitude                        95461 non-null  float64
 7   longitude                       95461 non-null  float64
 8   room_type                       95461 non-null  str    
 9   price                           64230 non-null  float64
 10  minimum_nights                  95461 non-null  int64  
 11  number_of_reviews               95461 non-null  int64  
 12  last_review                     68319 non-n

**Filtres logiques : garde uniquement les logements où :**
- price entre 20 et 1000 (on enlève les valeurs aberrantes)
- minimum_nights <= 30

In [7]:
df = df[(df["price"]> 20) & (df["price"] < 1000) & (df["minimum_nights"] <= 30)]

**Top 10 quartiers par prix médian :**

In [8]:
df.groupby("neighbourhood")["price"].median().sort_values(ascending=False).head(10)

neighbourhood
Élysée            240.0
Louvre            221.0
Luxembourg        220.0
Palais-Bourbon    219.0
Hôtel-de-Ville    200.0
Passy             197.0
Temple            190.0
Opéra             180.0
Bourse            180.0
Panthéon          179.0
Name: price, dtype: float64

**Bonus : Prix médian par room_type (Entire home, Private room, etc.).**

In [11]:
df.groupby("room_type")["price"].median().sort_values(ascending=False)

room_type
Hotel room         268.0
Entire home/apt    159.0
Private room       107.0
Shared room         52.0
Name: price, dtype: float64

Le jeu de données porte sur les airbnb à Paris. Le but de l'analyse est de suivre le prix médian.
Si nous regardons les 10 quartiers les plus chers en fonction du prix médians nous obtenons :
- Élysée  240.0€
- Louvre 221.0€
- Luxembourg 220.0€
- Palais-Bourbon 219.0€
- Hôtel-de-Ville 200.0€
- Passy 197.0€
- Temple 190.0€
- Opéra 180.0€
- Bourse 180.0€
- Panthéon 179.0€

Maintnenant regrdons le prix médian par type de chambre du plus chers au moins chers. Nous obtenons les Hotel room à 268.0€, Entire home/apt à 159.0€, Private room à 107.0€ et 
Shared room à 52.0€.